### PR TITLE
resolves #16 ignore when match is equals to replacement

### LINKED ISSUE #16: [proposal] Ignore match when the alternative is the same
I'm using this rule as a replacement of [Vale's `substitution` rule](https://docs.errata.ai/vale/styles#substitution).

I'm using the following definition to make sure that "Asciidoctor" and "AsciiDoc" have the correct casing: 

```json
{
  "rules": {
    "stop-words": {
      "defaultWords": false,
      "skip": ["Blockquote"],
      "words": [
        ["asciidoctor", "Asciidoctor"],
        ["asciidoc", "AsciiDoc"]
      ]
    }
  }
}
```

Since this rule allows to define replacement/alternative. I think it would be useful to check that the replacement/alternative is not strictly equals to the match.

Under this proposal, the following sentence will report an error:

```
AsciiDoctor is great!
     ^
```

But the following will not:

```
Asciidoctor is great!
```

### PR DESCRIPTION
**Pull request by Mogztter**
Allow to check that a word has the correct capitalization.

resolves #16

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -45,14 +45,16 @@ function reporter(context, options = {}) {
...
-							const message = `Avoid using “${word}”, use “${alternative}” instead`;
-							report(node, new RuleError(message, { index, fix }));
+							if (alternative !== matchedWord) {
+								const replacement = matched.replace(
+									matchedWord,
+									cloneCase(alternative, matchedWord)
+								);
+								const range = [index, index + matched.length];
+								const fix = fixer.replaceTextRange(range, replacement);
+								const message = `Avoid using “${matchedWord}”, use “${alternative}” instead`;
```
Comment (Mogztter) [inline index.js:55]: I'm using `matchedWord` instead of `word` otherwise the report is confusing when we want to check the capitalization.
For instance, given the following definition: `Asciidoctor > Asciidoctor` and the sentence: `AsciiDoctor is great` it will report:

```
Avoid using “Asciidoctor”, use “Asciidoctor” instead
```


With this change it will report:


```
Avoid using “AsciiDoctor”, use “Asciidoctor” instead
```

**Comment by sapegin** [comment]
Thanks!
